# Generated by Django 4.1 on 2022-08-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('empid', models.IntegerField()),
                ('mob', models.IntegerField()),
                ('psd', models.CharField(max_length=15)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HRMAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('psd', models.CharField(max_length=15)),
                ('hrid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='leavreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltype', models.CharField(max_length=30)),
                ('ldays', models.IntegerField()),
                ('lmsg', models.CharField(max_length=30)),
                ('lid', models.IntegerField()),
            ],
        ),
    ]
